### PR TITLE
Fix #54 book creation

### LINKED ISSUE #54: Book creation doesn't work
When trying to save a new book, the organization field is wiped and the following error appears:

image

Perhaps any kind of silent validation?

### PR DESCRIPTION
**Pull request by fedescarpa**
fixes #54

### CODE REVIEW

File: src/scripts/services/permissions-service.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ angular
     };
 
     this.isSuperUser = () => {
-      return this.isOwner('*');
+      return this.isWriter('*');
```
Comment (aguspina) [inline src/scripts/services/permissions-service.js]: @fedescarpa I don't think this is right. In fact, since owner permission exists, the SuperUser concept is useless. We should change the logic in the book controller not this name.

Comment (fedescarpa) [inline src/scripts/services/permissions-service.js]: I need it... maybe `isSuperUser` is not the best name... I will rename it
